version: "3.7"
services:
    jena-fuseki:
        container_name: jena-fuseki
        build: .
        restart: always
        ports: 
            - "3030:3030"
        volumes:
            - fuseki:/app
        environment: 
            - ADMIN_PASSWORD=pw345
volumes:
    fuseki:
        name: fuseki